server:
  port: 8081

spring:
  application:
    name: boardDemo
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      pool-name: HikariPool
      connection-timeout: 30000
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

